language: node_js 
install:          # List of any install commands required before script execution
- npm install --silent 
script:           # List of commands to build our project
- npm run test
- npm run build
deploy:           # List of commands for deploy
provider: pages
skip-cleanup: true
github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
keep-history: true
local-dir: build