language: node_js 
node_js:
  - "stable"
cache:
  directories:
  - node_modules

# List of commands to build our project
script:           
  - npm test
  - npm run build

# List of commands for deploy
deploy:           
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
  local-dir: build
  keep-history: true
  on: 
    branch: master